project_id = "ndfcycalqzjtgwkldafi"

[functions.generate-ai-reading-cards]
verify_jwt = false

[functions.generate-reading-cards-openai]
verify_jwt = false

[functions.ai-text-transform]
verify_jwt = false