// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndfcycalqzjtgwkldafi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZmN5Y2FscXpqdGd3a2xkYWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MTA5MzEsImV4cCI6MjA3NTM4NjkzMX0.4EvTuXk2mNC3yJF-LPuUfv_hxvfloQycjYsYjb818Xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});