// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mprwhgypstsjojmmzubz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wcndoZ3lwc3Rzam9qbW16dWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzE2MTAsImV4cCI6MjA3Mjg0NzYxMH0.yHqgcDneK_6LSCq2dV5ohkuam-t_ekJ-uuwhZJaTdio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});